odiseo_blog_partial_comment_create:
    path: /{articleId}/comment/new
    methods: [GET, POST]
    defaults:
        _controller: odiseo_blog.controller.article_comment:createAction
        _sylius:
            event: article_comment_create
            template: $template
            form:
                type: Odiseo\BlogBundle\Form\Type\ArticleUserCommentType
                options:
                    validation_groups: [odiseo_user_comment]
            factory:
                method: createNewWithArticle
                arguments: [$articleId]
            redirect:
                route: $redirectRoute
                parameters: $redirectParameters
