sylius_grid:
    grids:
        odiseo_blog_article_comment:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_blog.model.article_comment.class%"
            sorting:
                id: desc
            fields:
                id:
                    type: string
                    sortable: ~
                comment:
                    type: string
                    sortable: ~
                enabled:
                    type: string
                    sortable: ~
                createdAt:
                    type: datetime
                    sortable: ~
            filters:
                comment:
                    type: string
                enabled:
                    type: boolean
            actions:
                item:
                    update:
                        type: update
                    delete:
                        type: delete
