sylius_grid:
    grids:
        odiseo_blog_article:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_blog.model.article.class%"
            sorting:
                id: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                title:
                    type: twig
                    label: sylius.ui.title
                    path: .
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.creation_date
                    sortable: ~
            filters:
                title:
                    type: string
                    label: sylius.ui.title
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
