Odiseo\BlogBundle\Model\ArticleCategory:
    type: mappedSuperclass
    table: odiseo_blog_article_category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            unique: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        articles:
            targetEntity: Odiseo\BlogBundle\Model\ArticleInterface
            mappedBy: categories